### ISSUE TITLE
Worked on UDM SE with 3.0.18!!!!!

### ISSUE THREAD

**Issue by mnsaddict** [renedis/ubnt-auto-fan-speed#8]
After some tests it was finally silenced with the following values on fancontrol file.

# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=1
DEVPATH=hwmon0=devices/platform/soc/fd880000.i2c-pld/i2c-0/i2c-4/4-002e
DEVNAME=hwmon0=adt7475
FCTEMPS=hwmon0/device/pwm2=hwmon0/device/temp1_input hwmon0/device/pwm1=hwmon0/device/temp3_input
FCFANS=hwmon0/device/pwm2=hwmon0/device/fan4_input hwmon0/device/pwm1=hwmon0/device/fan1_input
MINTEMP=hwmon0/device/pwm2=60 hwmon0/device/pwm1=60
MAXTEMP=hwmon0/device/pwm2=66 hwmon0/device/pwm1=66
MINSTART=hwmon0/device/pwm2=60 hwmon0/device/pwm1=60
MINSTOP=hwmon0/device/pwm2=60 hwmon0/device/pwm1=0
MINPWM=hwmon0/device/pwm2=60 hwmon0/device/pwm1=0
MAXPWM=hwmon0/device/pwm2=255 hwmon0/device/pwm1=255

Thank you so much!!!!!!!

**Comment by mojo333** [comment]
Just to add I've just updated my UDM PRO to 2.5.16 (literally just released today 21/02) and it continues to work! Very happy with this.

**Comment by nulant** [comment]
Could you maybe please assist me how to make changes to the configuration file?
I would like to increase the minimum CPU fan % to decrease CPU temp.
It won't take my changes: MINPWM=hwmon0/device/pwm2=110.
Restart the service leads to: Job for fancontrol.service failed because the control process exited with error code.
See "systemctl status fancontrol.service" and "journalctl -xe" for details.

Thank you in advance, Thomas
